interface LookupTable {
    StS: number;
    percentile: number;
    category: string;
  }
  
  export const lookupTable: LookupTable[] = [
    { StS: 40, percentile: 1, category: 'SI' },
    { StS: 41, percentile: 1, category: 'SI' },
    { StS: 42, percentile: 1, category: 'SI' },
    { StS: 43, percentile: 1, category: 'SI' },
    { StS: 44, percentile: 1, category: 'SI' },
    { StS: 45, percentile: 1, category: 'SI' },
    { StS: 46, percentile: 1, category: 'SI' },
    { StS: 47, percentile: 1, category: 'SI' },
    { StS: 48, percentile: 1, category: 'SI' },
    { StS: 49, percentile: 1, category: 'SI' },
    { StS: 50, percentile: 1, category: 'SI' },
    { StS: 51, percentile: 1, category: 'SI' },
    { StS: 52, percentile: 1, category: 'SI' },
    { StS: 53, percentile: 1, category: 'SI' },
    { StS: 54, percentile: 1, category: 'SI' },
    { StS: 55, percentile: 1, category: 'SI' },
    { StS: 56, percentile: 1, category: 'SI' },
    { StS: 57, percentile: 1, category: 'SI' },
    { StS: 58, percentile: 1, category: 'SI' },
    { StS: 59, percentile: 1, category: 'SI' },
    { StS: 60, percentile: 1, category: 'SI' },
    { StS: 61, percentile: 1, category: 'SI' },
    { StS: 62, percentile: 1, category: 'SI' },
    { StS: 63, percentile: 1, category: 'SI' },
    { StS: 64, percentile: 1, category: 'SI' },
    { StS: 65, percentile: 1, category: 'SI' },
    { StS: 66, percentile: 1, category: 'SI' },
    { StS: 67, percentile: 1, category: 'SI' },
    { StS: 68, percentile: 2, category: 'Mod Imp' },
    { StS: 69, percentile: 2, category: 'Mod Imp' },
    { StS: 70, percentile: 2, category: 'Mod Imp' },
    { StS: 71, percentile: 3, category: 'Mild Imp' },
    { StS: 72, percentile: 3, category: 'Mild Imp' },
    { StS: 73, percentile: 4, category: 'Mild Imp' },
    { StS: 74, percentile: 4, category: 'Mild Imp' },
    { StS: 75, percentile: 5, category: 'Mild Imp' },
    { StS: 76, percentile: 5, category: 'Mild Imp' },
    { StS: 77, percentile: 6, category: 'Mild Imp' },
    { StS: 78, percentile: 7, category: 'Mild Imp' },
    { StS: 79, percentile: 8, category: 'Mild Imp' },
    { StS: 80, percentile: 9, category: 'LA' },
    { StS: 81, percentile: 10, category: 'LA' },
    { StS: 82, percentile: 12, category: 'LA' },
    { StS: 83, percentile: 13, category: 'LA' },
    { StS: 84, percentile: 14, category: 'LA' },
    { StS: 85, percentile: 16, category: 'LA' },
    { StS: 86, percentile: 18, category: 'LA' },
    { StS: 87, percentile: 19, category: 'LA' },
    { StS: 88, percentile: 21, category: 'LA' },
    { StS: 89, percentile: 23, category: 'A' },
    { StS: 90, percentile: 25, category: 'A' },
    { StS: 91, percentile: 27, category: 'A' },
    { StS: 92, percentile: 30, category: 'A' },
    { StS: 93, percentile: 32, category: 'A' },
    { StS: 94, percentile: 34, category: 'A' },
    { StS: 95, percentile: 37, category: 'A' },
    { StS: 96, percentile: 39, category: 'A' },
    { StS: 97, percentile: 42, category: 'A' },
    { StS: 98, percentile: 45, category: 'A' },
    { StS: 99, percentile: 47, category: 'A' },
    { StS: 100, percentile: 50, category: 'A' },
    { StS: 101, percentile: 53, category: 'A' },
    { StS: 102, percentile: 55, category: 'A' },
    { StS: 103, percentile: 58, category: 'A' },
    { StS: 104, percentile: 61, category: 'A' },
    { StS: 105, percentile: 63, category: 'A' },
    { StS: 106, percentile: 66, category: 'A' },
    { StS: 107, percentile: 68, category: 'A' },
    { StS: 108, percentile: 70, category: 'A' },
    { StS: 109, percentile: 73, category: 'A' },
    { StS: 110, percentile: 75, category: 'HA' },
    { StS: 111, percentile: 77, category: 'HA' },
    { StS: 112, percentile: 79, category: 'HA' },
    { StS: 113, percentile: 81, category: 'HA' },
    { StS: 114, percentile: 82, category: 'HA' },
    { StS: 115, percentile: 84, category: 'HA' },
    { StS: 116, percentile: 86, category: 'HA' },
    { StS: 117, percentile: 87, category: 'HA' },
    { StS: 118, percentile: 88, category: 'HA' },
    { StS: 119, percentile: 90, category: 'HA' },
    { StS: 120, percentile: 91, category: 'Sup' },
    { StS: 121, percentile: 92, category: 'Sup' },
    { StS: 122, percentile: 93, category: 'Sup' },
    { StS: 123, percentile: 94, category: 'Sup' },
    { StS: 124, percentile: 95, category: 'Sup' },
    { StS: 125, percentile: 95, category: 'Sup' },
    { StS: 126, percentile: 96, category: 'Sup' },
    { StS: 127, percentile: 96, category: 'Sup' },
    { StS: 128, percentile: 96, category: 'Sup' },
    { StS: 129, percentile: 97, category: 'Sup' },
    { StS: 130, percentile: 97, category: 'VS' },
    { StS: 131, percentile: 98, category: 'VS' },
    { StS: 132, percentile: 98, category: 'VS' },
    { StS: 133, percentile: 99, category: 'VS' }
  ];